services:
  db:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
volumes:
  pgdata:
    name: pgdata
